### ISSUE TITLE
Investigation vs Project in NIDM-Experiment

### ISSUE THREAD

**Issue by khelm** [incf-nidash/nidm#405]
@dbkeator you mentioned using Investigation as your top level and the lucidchart for NIDM-Experiment uses Project.  I'm using Project because SIO's definition of Investigation is "investigation is the process of carrying out a plan or procedure...", which to me sounds like an Activity rather than an Entity.  SIO also says that Investigation and Study are synonyms.  {SIO Study = "a process that realizes the steps of a study design", also an activity}

On the other hand:
Project - National Cancer Institute Thesaurus (NCIT)
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C47885
Any specifically defined piece of work that is undertaken or attempted to meet a single requirement.

**Comment by tiborauer** [comment]
We had similar discussion on our last Workflow meeting. As Satra pointed out, the question is whether you want to refer to the description (“noun”) or the execution (“verb”).

Vale,
Tibor

Auer, Tibor M.D. Ph.D.
Research Fellow in MRI
Department of Psychology
Royal Holloway University of London
Egham Hill
Egham
TW20 0EX
United Kingdom
[cid:image001.jpg@01D04F5F.0CADAB60] +44-1784-27-6594
[cid:image002.jpg@01D04F5F.0CADAB60] Tibor.Auer@rhul.ac.uk<mailto:Tibor.Auer@rhul.ac.uk>

[royalhollowaylogo]<https://www.royalholloway.ac.uk/psychology/home.aspx>

**Comment by khelm** [comment]
Yes, exactly.  In this case it's the noun.

**Comment by satra** [comment]
@khelm - we just had a discussion about this as well. i think it would be good to consider the options. as part of the work @smpadhy is doing, we are considering projects as activities comprising of sub-activities (sessions, logical sessions, etc.,.) as @tiborauer points out we just had this discussion in the context of nidm workflow. 

my personal preference would be to treat a project as an activity since it typically has a start date and end date. after all, a project or investigation is a workflow, just with different types of processes.

**Comment by satra** [comment]
@khelm - and in this thread, to use the term `project` (a bit more general) than an `investigation`
