### ISSUE TITLE
NIDM_0000155 - fMRI Design Type

### ISSUE THREAD

**Issue by khelm** [incf-nidash/nidm#436]
NIDM-Exp ontology uses `fMRI Design Type`, but I don't see this term in NIDM Results terms file.  Is this an actual used term or has it been deprecated?

**Comment by cmaumet** [comment]
@khelm: that's correct this term is no longer used in NIDM-Results. The reason is that we decided that NIDM-Results should focus only on attributes that can be automatically retrieved (and definition of event/block/mixed design can vary). 

We moved this term to NIDM-Experiment draft ontology as we thought this could be a useful info that the user could provide. For more background, the original discussion is here: https://github.com/incf-nidash/nidm/pull/358

**Comment by khelm** [comment]
Thanks @cmaumet.  It's currently in the right place, but just wanted to check to make sure it was a valid term.
